# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
animals = Animal.create([
    {name: 'antelopes', group: 'herd'},
    {name: 'ants', group: 'army, colony, nest, swarm'},
    {name: 'apes', group: 'shrewdness, troop '},
    {name: 'donkeys', group: 'herd, drove, pace'},
    {name: 'baboons', group: 'troop'},
    {name: 'badgers', group: 'cete'},
    {name: 'bats', group: 'colony'},
    {name: 'bears', group: 'sleuth or sloth'},
    {name: 'beavers', group: 'colony, family '},
    {name: 'bees', group: 'swarm, drift, Hum, grist'},
    {name: 'birds', group: 'flock, flight, pod'},
    {name: 'bitterns', group: 'sedge or sege'},
    {name: 'boars', group: 'sounder'},
    {name: 'buffaloes', group: 'herd'},
    {name: 'bullfinches', group: 'bellowing'},
    {name: 'bullocks', group: 'drove'},
    {name: 'butterflies', group: 'swarm, flutter, kaleidoscope'},
    {name: 'capercaillie', group: 'tok'},
    {name: 'capons', group: 'mews'},
    {name: 'caribou', group: 'herd'},
    {name: 'cats', group: 'clowder, glaring, pounce, destruction'},
    {name: 'cattle', group: 'mob'},
    {name: 'chickens', group: 'clutch'},
    {name: 'cheetahs', group: 'coalition or band'},
    {name: 'choughs', group: 'chattering or clatterin'},
    {name: 'colts', group: 'rag, rake'},
    {name: 'cormorants', group: 'gulp'},
    {name: 'coots', group: 'covert'},
    {name: 'coyotes', group: 'pack'},
    {name: 'cranes', group: 'herd, sedge or sege, siege'},
    {name: 'crocodiles', group: 'bask'},
    {name: 'crows', group: 'murder, horde or wake (when feeding)'},
    {name: 'curlews', group: 'herd'},
    {name: 'deer', group: 'herd, parcel'},
    {name: 'dogs', group: 'pack'},
    {name: 'dolphins', group: 'pod'},
    {name: 'dotterel', group: 'trip'},
    {name: 'doves', group: 'dole or dule, flight'},
    {name: 'ducks', group: 'badling or badelynge, paddling, plump, raft'},
    {name: 'dunlins', group: 'fling'},
    {name: 'eagles', group: 'convocation'},
    {name: 'eels', group: 'bed'},
    {name: 'elephants', group: 'herd'},
    {name: 'elk', group: 'gang, herd'},
    {name: 'falcons', group: 'cast'},
    {name: 'ferrets', group: 'business, busyness, besyness, fesynes, fesnyng, feamyng'},
    {name: 'finches', group: 'charm or chirm'},
    {name: 'fish', group: 'school, shoal '},
    {name: 'flamingoes', group: 'stand, flamboyance, colony, regiment'},
    {name: 'flies', group: 'business'},
    {name: 'foxes', group: 'leash, skulk '},
    {name: 'frogs', group: 'army'},
    {name: 'geese', group: 'gaggle'},
    {name: 'giraffes', group: 'tower'},
    {name: 'gnats', group: 'cloud, horde'},
    {name: 'goats', group: 'flock, trip'},
    {name: 'goldfinches', group: 'charm'},
    {name: 'gopher', group: 'slice'},
    {name: 'gorillas', group: 'band'},
    {name: 'goshawks', group: 'flight'},
    {name: 'grackles', group: 'plague'},
    {name: 'grasshoppers', group: 'cloud'},
    {name: 'grouse', group: 'covey'},
    {name: 'guineafowl', group: 'rasp'},
    {name: 'haggises', group: 'conspiracy'},
    {name: 'hawks', group: 'boil, cast, kettle, lease, brood'},
    {name: 'hens', group: 'brood'},
    {name: 'herons', group: 'siege'},
    {name: 'hippopotamuses', group: 'pod, bloat or herd'},
    {name: 'hogs', group: 'parcel'},
    {name: 'hornets', group: 'nest'},
    {name: 'horses', group: 'string, stud, team, haras'},
    {name: 'hounds', group: 'pack'},
    {name: 'hyenas', group: 'clan'},
    {name: 'ibex', group: 'herd'},
    {name: 'jellyfish', group: 'fluther, smack'},
    {name: 'kangaroos', group: 'mob, troop, kindle'},
    {name: 'leopards', group: 'leap or lepe'},
    {name: 'lions', group: 'pride'},
    {name: 'locusts', group: 'plague'},
    {name: 'magpies', group: 'charm, gulp, murder, tiding'},
    {name: 'mallards', group: 'sord, suit or sute, flush,'},
    {name: 'mice', group: 'nest'},
    {name: 'moles', group: 'labor'},
    {name: 'monkeys', group: 'barrel,troop,wilderness'},
    {name: 'moose', group: 'herd'},
    {name: 'mules', group: 'barren, span'},
    {name: 'nightingales', group: 'watch'},
    {name: 'octopuses', group: 'rally'},
    {name: 'opossums', group: 'passel'},
    {name: 'owls', group: 'parliament'},
    {name: 'oxen', group: 'yoke'},
    {name: 'oysters', group: 'bed'},
    {name: 'parrots', group: 'company, pandemonium'},
    {name: 'partridges', group: 'covey'},
    {name: 'peacocks', group: 'muster, ostentation'},
    {name: 'pelicans', group: 'pod'},
    {name: 'penguins', group: 'colony, convent, creche, raft, tuxedo,'},
    {name: 'pheasants', group: 'bouquet, head, nest, nide, nye,'},
    {name: 'pigs', group: 'drift, drove'},
    {name: 'pigeons', group: 'kit'},
    {name: 'platypuses', group: 'pandemonium'},
    {name: 'plovers', group: 'congregation, stand, wing'},
    {name: 'quail', group: 'covey'},
    {name: 'rabbits', group: 'colony, nest, herd, litter'},
    {name: 'raccoons', group: 'gaze'},
    {name: 'rats', group: 'mischief'},
    {name: 'ravens', group: 'unkindness'},
    {name: 'rhinoceroses', group: 'crash or herd'},
    {name: 'rooks', group: 'parliament'},
    {name: 'seals', group: 'pod'},
    {name: 'sea urchins', group: 'herd'},
    {name: 'seagull', group: 'squabble'},
    {name: 'sharks', group: 'shiver'},
    {name: 'sheep', group: 'flock'},
    {name: 'sheldrake', group: 'dopping'},
    {name: 'snakes', group: 'pit'},
    {name: 'spiders', group: 'cluster or clutter'},

])
